name: Update Screenshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-screenshot:
    name: Update Screenshot
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up node cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Puppeteer cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer

      - name: Install
        run: npm ci

      - name: Update Screenshot
        uses: otaly/readme-screenshot-action@v1.0.0
        with:
          urls: http://localhost:5173/
          server_command: npm run dev
          delay: 3000

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update screenshots
